apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysqldb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb
        tier: database
    spec:
      containers:
      - name: mysqldb
        image: dockermrj33/portfolio-manager-db:latest
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 3306
            name: mysqldb
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-db-name
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    tier: database
spec:
  selector:
    app: mysqldb
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None