apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: dockermrj33/portfolio-manager-web:1.0.9
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: base-url
---
apiVersion: v1
kind: Service
metadata: 
  name: webapp-service
spec:
  type: NodePort
  selector: 
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30101